server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #server-addr: 192.168.1.5:1111 #nginx代理nacos地址
        server-addr: 192.168.1.5:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
