server:
  port: 2003

spring:
  application:
    name: seata-account-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.5:8848 #Nacos服务注册中心地址
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.5:3306/seata_account?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  #config-location: classpath:mapper/*.xml
  type-aliases-package: com.qibria.cloud.alibaba.domain
  mapper-locations: classpath:mapper/*.xml

feign:
  hystrix:
    enabled: false


logging:
  level:
    io:
      seata: info
  file:
    name: ./account.log

## seata 属性配置
seata:
  enabled: true
  tx-service-group: custom_test_tx_group
  # 是否自动开启数据源代理
  enable-auto-data-source-proxy: true
  # 数据源代理模式，使用AT模式
  data-source-proxy-mode: AT
  client:
    rm:
      lock:
        # 校验或占用全局锁重试间隔，单位ms
        retry-interval: 10
        # 校验或占用全局锁重试次数
        retry-times: 30
        # 分支事务与其它全局回滚事务冲突时锁策略,true，优先释放本地锁让回滚成功
        retry-policy-branch-rollback-on-conflict: true
    tm:
      # 一阶段全局提交结果上报TC重试次数
      commit-retry-count: 5
      # 一阶段全局回滚结果上报TC重试次数
      rollback-retry-count: 5
      # 分布式事物超时时间
      default-global-transaction-timeout: 600000
      # 降级开关,false 不打开
      degrade-check: false
      degrade-check-period: 2000
      degrade-check-allow-times: 10
    undo:
      log-serialization: jackson
  # 注册中心，需要和 seata server 保持一致
  registry:
    type: nacos
    nacos:
      application: seata-server
      group: SEATA_GROUP
      server-addr: 192.168.1.5:8848
      username: nacos
      password: nacos
  # 配置中心，需要和 seata server 保持一致
  config:
    type: nacos
    nacos:
      serverAddr: 192.168.1.5:8848
      data-id: seataServer.properties
      group: SEATA_GROUP
  service:
    # 全局事务开关
    disable-global-transaction: false
    vgroupMapping:
      default_tx_group: default # default 集群
  log:
    exception-rate: 100
