server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.5:8848 #Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: 192.168.1.5:8080 #配置Sentinel dashboard地址
        port: 8719 #sentinel 会启动一个服务与dashboard面板通信，如果端口被占用会自动+1知道找到没有被占用端口，默认就是8719
        client-ip: 192.168.1.4 # 本机ip
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.1.5:8848
            dataId: cloudalibaba-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true # 激活Sentinel对Feign的支持
