server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.5:8848 #Nacos服务注册中心地址
management:
  endpoints:
    web:
      exposure:
        include: '*'

### seata 属性配置
seata:
  enabled: true
  tx-service-group: default_tx_group
  registry:
    nacos:
      group: SEATA_GROUP
      server-addr: 192.168.1.5:8848
  service:
    disable-global-transaction: false
    vgroupMapping:
      default_tx_group: default



